############################################
# Spring AI Ollama
############################################



############################################
# Spring AI Z.AI
############################################
spring.ai.model.chat=openai
spring.ai.openai.base-url=https://api.z.ai/api/coding/paas/v4
spring.ai.openai.api-key=${ZAI_API_KEY}
spring.ai.openai.chat.options.model=glm-4.7
spring.ai.openai.chat.options.temperature=0.0
spring.ai.openai.chat.options.response-format=json_object

############################################
# Vector Store Config
############################################
agenticrouter.vectorstore.ingestion.ingest-batch-size=1000
agenticrouter.vectorstore.ingestion.split-chunk-size=1600
agenticrouter.vectorstore.ingestion.split-min-chunk-size-chars=300
agenticrouter.vectorstore.ingestion.split-min-chunk-length-to-embed=50
agenticrouter.vectorstore.ingestion.progress-update-interval-ms=1000
