############################################
# Spring AI Ollama
############################################
# Model + generation params
spring.ai.ollama.chat.options.model=qwen3:4b

############################################
# Spring AI Z.AI
############################################
