BEGIN;

WITH ts AS (SELECT now() AS now_ts)
INSERT
INTO policy_config
(row_version,
 created_at,
 updated_at,
 config_key,
 config_value,
 description,
 active,
 default_value,
 min_value,
 max_value)
VALUES
  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'AUTO_ROUTE_THRESHOLD',
   0.70,
   'Minimum confidence threshold for auto-routing',
   TRUE,
   0.70,
   0.00,
   1.00),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'CRITICAL_MIN_CONF',
   0.85,
   'Minimum confidence for CRITICAL priority tickets',
   TRUE,
   0.85,
   0.00,
   1.00),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'ROUTER_REPAIR_MAX_RETRIES',
   2,
   'Max JSON repair retries before HUMAN_REVIEW',
   TRUE,
   2,
   0,
   5),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'SLA_ASSIGNED_HOURS_HIGH',
   24,
   'Hours before reminding when assigned/in-progress high priority',
   TRUE,
   24,
   1,
   168),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'WAITING_CUSTOMER_REMINDER_HOURS',
   48,
   'Hours before reminding customer when waiting on customer response',
   TRUE,
   48,
   1,
   720),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'INACTIVITY_AUTO_CLOSE_DAYS',
   14,
   'Days of inactivity before auto-close workflow',
   TRUE,
   14,
   1,
   365),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'SLA_CUSTOMER_RESPONSE_HOURS',
   48,
   'Hours to wait for customer response before SLA breach',
   TRUE,
   48,
   1,
   720),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'SLA_AGENT_RESPONSE_HOURS',
   24,
   'Hours before agent response SLA breach',
   TRUE,
   24,
   1,
   168),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'AUTO_CLOSE_WARNING_DAYS',
   3,
   'Days of inactivity before auto-close warning',
   TRUE,
   3,
   1,
   30),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'AUTO_CLOSE_FINAL_DAYS',
   7,
   'Days of inactivity before auto-close resolved tickets',
   TRUE,
   7,
   1,
   90),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'MAX_ATTACHMENT_BYTES',
   52428800,
   'Max attachment size in bytes',
   TRUE,
   52428800,
   0,
   214748364800),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'AUTO_CLOSE_ENABLED',
   1,
   'Enable inactivity auto-close workflow',
   TRUE,
   1,
   0,
   1),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'DEFAULT_QUEUE',
   0,
   'Default routing queue key',
   TRUE,
   0,
   0,
   0),

  (0,
   (SELECT now_ts FROM ts),
   (SELECT now_ts FROM ts),
   'ROUTER_MODEL_PARAMS',
   0,
   'Model parameters for router inference',
   TRUE,
   0,
   0,
   0)
ON CONFLICT (config_key)
  DO UPDATE SET config_value  = EXCLUDED.config_value,
                description   = EXCLUDED.description,
                active        = EXCLUDED.active,
                default_value = EXCLUDED.default_value,
                min_value     = EXCLUDED.min_value,
                max_value     = EXCLUDED.max_value,
                updated_at    = (SELECT now_ts FROM ts)
WHERE policy_config.config_value IS DISTINCT FROM EXCLUDED.config_value
   OR policy_config.description IS DISTINCT FROM EXCLUDED.description
   OR policy_config.active IS DISTINCT FROM EXCLUDED.active
   OR policy_config.default_value IS DISTINCT FROM EXCLUDED.default_value
   OR policy_config.min_value IS DISTINCT FROM EXCLUDED.min_value
   OR policy_config.max_value IS DISTINCT FROM EXCLUDED.max_value;

COMMIT;
