-- =====================================================
-- Knowledge Base Seeding - Representative Sample
-- Total: 100+ articles, 200+ templates
-- =====================================================

BEGIN;

-- =====================================================
-- BILLING ARTICLES (180 total)
-- =====================================================

INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Update Payment Method',
        'To update your payment method: 1. Go to Settings > Billing 2. Click "Payment Method" 3. Add new card or update existing 4. Save changes',
        'BILLING',
        10,
        ARRAY ['payment', 'credit card', 'update'],
        'SOLUTION',
        true,
        0,
        0,
        0),
       ('View and Pay Invoice',
        'To view your invoice: 1. Go to Settings > Billing 2. Click "Invoices" 3. Select the invoice you want to view 4. Download PDF or view details',
        'BILLING',
        9,
        ARRAY ['invoice', 'pdf', 'view'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Subscription Plans',
        'Available plans: FREE (basic features), STANDARD (full access), PREMIUM (priority support), ENTERPRISE (custom solutions). To change plans: Go to Settings > Subscription > Manage Plan > Select new plan > Confirm.',
        'BILLING',
        8,
        ARRAY ['subscription', 'plans', 'upgrade', 'downgrade'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Subscription Renewal',
        'Your subscription will auto-renew on renewal date. You can view your renewal date and payment method in Settings > Billing. To change auto-renewal: Go to Settings > Billing > Subscription Settings > Toggle auto-renewal',
        'BILLING',
        7,
        ARRAY ['renewal', 'auto-renew', 'billing date'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Request Refund',
        'To request a refund: 1. Go to your order history or invoice list 2. Select the item you want refunded 3. Submit refund request with reason 4. Wait for approval (typically 5-7 business days)',
        'BILLING',
        6,
        ARRAY ['refund', 'request', 'approval', 'policy'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Payment Failed Error',
        'If your payment failed: 1. Check if you have sufficient funds 2. Verify card details are correct 3. Try a different payment method 4. Contact support if issue persists. Common failed reasons: insufficient funds, expired card, network error',
        'BILLING',
        5,
        ARRAY ['payment failed', 'error', 'card', 'network'],
        'TROUBLESHOOTING',
        true,
        0,
        0,
        0),
       ('Auto-Charge Failed',
        'If auto-charge failed: 1. Contact support immediately 2. Check payment method is still valid 3. Update payment information',
        'BILLING',
        4,
        ARRAY ['auto-charge', 'subscription', 'update'],
        'TROUBLESHOOTING',
        true,
        0,
        0,
        0),
       ('Billing Address Update',
        'To update billing address: 1. Go to Settings > Billing 2. Update address field 3. Save changes',
        'BILLING',
        3,
        ARRAY ['address', 'billing', 'update'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Tax ID Update',
        'To add tax ID for business: 1. Go to Settings > Billing 2. Add Tax ID in designated field 3. Provide business verification documents if needed',
        'BILLING',
        2,
        ARRAY ['tax', 'vat', 'business id'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Billing History',
        'View your billing history: Go to Settings > Billing > View All Transactions. Shows: payment date, amount, payment method, invoice link. Export available.',
        'BILLING',
        2,
        ARRAY ['history', 'transactions', 'export'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Invoice Explanation',
        'Understanding your invoice: Each invoice includes: Account Summary (services, credits, charges), Payment Breakdown (subtotal, tax, total), Due Date, Payment Methods',
        'PRICING',
        5,
        ARRAY ['invoice', 'explanation', 'charges', 'due date'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Prorated Refund Policy',
        'Refund policy based on subscription tier: FREE: No refund, STANDARD: 7-day refund policy, PREMIUM: 14-day refund policy, ENTERPRISE: 30-day refund policy',
        'BILLING',
        6,
        ARRAY ['prorated', 'refund policy', 'tier'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Late Payment Fee',
        'Late payments may incur: Fee applies if payment is > 7 days past due date. Avoid late fees by setting up auto-pay or paying on time. Fee: Percentage of monthly payment (varies by tier).',
        'BILLING',
        5,
        ARRAY ['late payment', 'fee', 'auto-pay', 'due date'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Multiple Invoices',
        'Multiple invoices can be combined: Go to Settings > Billing > select multiple invoices > Pay Selected. Or let them be auto-charged together.',
        'BILLING',
        4,
        ARRAY ['multiple', 'invoices', 'combine', 'pay together'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Payment Timing',
        'Payment processing time: Credit cards: 1-3 business days, PayPal: Instant, Bank transfer: 3-5 business days. Auto-charge available.',
        'BILLING',
        4,
        ARRAY ['processing time', 'credit card', 'paypal', 'bank transfer', 'auto-charge'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Account Balance',
        'View your balance: Go to Settings > Billing > Account Balance. Shows credits and pending charges. Can pay invoices from balance or set auto-pay from balance.',
        'BILLING',
        3,
        ARRAY ['balance', 'credits', 'auto-pay', 'pay from'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Currency Support',
        'Multi-currency support: Currently we support USD and EUR. Select your currency preference during sign-up.',
        'BILLING',
        2,
        ARRAY ['currency', 'USD', 'EUR', 'multi'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Billing Support Contact',
        'Billing support hours: 24/7 email support. Response time: < 24 hours. For urgent issues, create ticket directly.',
        'BILLING',
        3,
        ARRAY ['support', 'hours', 'contact', 'response time', 'email'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Discount Application',
        'Apply discount codes: Have a discount code? Enter it at checkout or in Settings > Billing. Cannot combine with other offers.',
        'BILLING',
        4,
        ARRAY ['discount', 'code', 'apply', 'combine'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Gift Card/Redemption',
        'Gift card or credit redemption: Enter code at checkout. Credit applied to your balance immediately.',
        'BILLING',
        3,
        ARRAY ['gift card', 'credit', 'redeem', 'code', 'balance'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Split Payment',
        'Split payments: Enable at checkout. Choose how to split: by payment method (equal amounts) or by invoice item.',
        'BILLING',
        3,
        ARRAY ['split payment', 'equal', 'invoice', 'checkout'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0);

COMMIT;

-- =====================================================
-- TECHNICAL ARTICLES (200 total)
-- =====================================================

BEGIN;

INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Password Reset Instructions',
        'I have reset your password. Please follow these steps to log in: 1. Go to login page 2. Enter your email address and temporary password 3. Click "Login" 4. You will be prompted to create a new password immediately 5. Create a strong password (minimum 8 characters, mix of letters, numbers, and symbols) 6. Confirm new password',
        'TECHNICAL',
        10,
        ARRAY ['password', 'reset', 'login', 'change', 'security'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Account Unlock',
        'Your account is locked after 5 failed login attempts. To unlock: 1. Click "Forgot Password" on login page 2. Enter your registered email address 3. You will receive an unlock link via email 4. Click link in the email to reset your password 5. Log in with your new password',
        'TECHNICAL',
        9,
        ARRAY ['account', 'locked', 'unlock', 'reset password', 'failed login'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('2FA Setup',
        'Enable two-factor authentication: Go to Settings > Account > Security > Enable 2FA. You can use authenticator app (Google Authenticator, Microsoft Authenticator, or SMS). Required for PREMIUM and ENTERPRISE tiers.',
        'TECHNICAL',
        8,
        ARRAY ['2fa', 'security', 'authenticator', 'sms', 'google', 'microsoft'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Profile Update',
        'Update your profile: Go to Settings > Account > Profile. Update your name, email, phone number, and address information.',
        'TECHNICAL',
        5,
        ARRAY ['profile', 'name', 'email', 'phone', 'address'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Email Change',
        'Change email address: Go to Settings > Account > Email. Click "Change Email" and enter new email address 2. Verify new email by entering verification code sent to current email 3. Confirm change. Note: Your old email becomes inactive.',
        'TECHNICAL',
        6,
        ARRAY ['email', 'change', 'verify', 'inactive'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Delete Account',
        'Close your account: Go to Settings > Account > Close Account. WARNING: This action cannot be undone. All your data will be deleted after 30 days.',
        'TECHNICAL',
        2,
        ARRAY ['delete', 'account', 'data', 'permanent'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Dashboard Navigation',
        'Dashboard overview: Access your dashboard by clicking menu icon. Shows: Ticket status, recent activity, quick links, and notifications. Customize dashboard layout in Settings.',
        'TECHNICAL',
        4,
        ARRAY ['dashboard', 'navigation', 'menu', 'layout', 'customize'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Ticket Creation',
        'Create a support ticket: Click "New Ticket" button. Fill in subject and describe your issue. Select category if applicable. Attach files if needed.',
        'TECHNICAL',
        10,
        ARRAY ['ticket', 'create', 'subject', 'category', 'attach files'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Ticket Status',
        'Track ticket progress: Status flow: RECEIVED -> TRIAGING -> WAITING_CUSTOMER -> ASSIGNED -> IN_PROGRESS -> RESOLVED/CLOSED. Check status in dashboard or via email notifications.',
        'TECHNICAL',
        7,
        ARRAY ['ticket', 'status', 'flow', 'tracking', 'notification'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('View Ticket Details',
        'View ticket details: Click on ticket to view full conversation history and details. See all messages, timestamps, and status changes.',
        'TECHNICAL',
        6,
        ARRAY ['ticket', 'details', 'history', 'timeline'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Reply to Ticket',
        'Respond to support: Add message by typing in text box or clicking reply. Attach files or screenshots. Mark as internal if not for customer.',
        'TECHNICAL',
        8,
        ARRAY ['ticket', 'reply', 'message', 'attach files', 'internal note'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Close Ticket',
        'Close resolved ticket: If issue is resolved, click "Close Ticket" button. Provide satisfaction rating if requested. Add resolution notes for future reference.',
        'TECHNICAL',
        5,
        ARRAY ['ticket', 'close', 'resolve', 'satisfaction', 'notes'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Reopen Ticket',
        'Reopen closed ticket: If issue persists after closure, reply to ticket. Ticket status changes to RECEIVED or TRIAGING. New ticket number generated for reopening.',
        'TECHNICAL',
        4,
        ARRAY ['ticket', 'reopen', 'closed', 'new number'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Escalation',
        'Escalate to supervisor: For urgent issues or when resolution requires escalation: 1. Contact support or create ticket with "escalation" in subject 2. Ticket will be routed to supervisor queue 3. Expected response time: Faster than standard queue',
        'TECHNICAL',
        6,
        ARRAY ['escalation', 'supervisor', 'urgent', 'response time'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Mobile App Troubleshooting',
        'App not loading: Clear app cache: 1. Force close and reopen app 2. Check internet connection 3. Update app to latest version 4. Reinstall if issue persists 5. Contact support with device details',
        'TECHNICAL',
        5,
        ARRAY ['mobile', 'app', 'cache', 'internet', 'version', 'reinstall'],
        'TROUBLESHOOTING',
        true,
        0,
        0,
        0),
       ('Notification Issues',
        'Not receiving notifications: 1. Check notification settings 2. Enable browser notifications 3. Check spam folder 4. Verify email address is correct',
        'TECHNICAL',
        4,
        ARRAY ['notification', 'settings', 'spam', 'browser', 'email'],
        'TROUBLESHOOTING',
        true,
        0,
        0,
        0),
       ('Sync Issues',
        'Data not syncing: 1. Refresh the page 2. Check internet connection 3. Try logout and login again 4. Wait a few minutes for sync to complete',
        'TECHNICAL',
        5,
        ARRAY ['sync', 'refresh', 'internet', 'logout', 'wait'],
        'TROUBLESHOOTING',
        true,
        0,
        0,
        0),
       ('Clear Cache/Cookies',
        'Performance issues: 1. Clear browser cache and cookies 2. Try incognito/private mode 3. Disable browser extensions temporarily',
        'TECHNICAL',
        3,
        ARRAY ['cache', 'cookies', 'browser', 'incognito', 'extensions'],
        'TROUBLESHOOTING',
        true,
        0,
        0,
        0),
       ('API Connection Errors',
        'API errors: If you see API errors: 1. Refresh the page 2. Check if service is operational 3. Contact support if issue persists with screenshot',
        'TECHNICAL',
        4,
        ARRAY ['api', 'error', 'refresh', 'service down', 'screenshot'],
        'TROUBLESHOOTING',
        true,
        0,
        0,
        0),
       ('Browser Compatibility',
        'Browser issues: Supported browsers: Chrome 80+, Firefox 75+, Safari 14+, Edge. Recommended browser: Chrome. Update browser regularly.',
        'TECHNICAL',
        4,
        ARRAY ['browser', 'chrome', 'firefox', 'safari', 'edge'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Platform Features',
        'Dashboard features: Activity Feed: Shows recent updates, tasks, and notifications. Analytics: View your account statistics and performance reports. Quick Actions: Quick access to common tasks (create ticket, view profile).',
        'TECHNICAL',
        5,
        ARRAY ['dashboard', 'activity feed', 'analytics', 'quick actions'],
        'FEATURE_OVERVIEW',
        true,
        0,
        0,
        0),
       ('Integrations',
        'Third-party integrations: CRM: View customer profiles and ticket history. Payment: Process payments and view invoices. Support: Access knowledge base articles.',
        'TECHNICAL',
        6,
        ARRAY ['integration', 'crm', 'payment', 'knowledge base', 'customer profile'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Security Best Practices',
        'Security guidelines: Strong passwords: Use at least 8 characters. Change regularly. 2FA: Enable two-factor authentication. Recognize phishing: Be cautious of emails asking for login credentials or payment information. Report suspicious emails.',
        'TECHNICAL',
        9,
        ARRAY ['security', 'phishing', 'password', '2fa', 'email'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Data Management',
        'Account data: You can export your data (tickets, profile, messages) from Settings. Data is retained for 30 days after account closure.',
        'TECHNICAL',
        5,
        ARRAY ['data', 'export', 'retention', 'GDPR'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Feature Updates',
        'New features: Stay informed about new features through dashboard notifications. Check release notes in Help Center.',
        'TECHNICAL',
        4,
        ARRAY ['features', 'new', 'release notes', 'help center'],
        'FEATURE_OVERVIEW',
        true,
        0,
        0,
        0),
       ('Troubleshooting Steps',
        'Common solutions: 1. Clear cache and cookies 2. Try different browser 3. Check internet connection 4. Disable extensions 5. Update app 6. Reinstall as last resort',
        'TECHNICAL',
        8,
        ARRAY ['troubleshooting', 'cache', 'browser', 'internet', 'extensions', 'app', 'reinstall'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0);

COMMIT;

-- =====================================================
-- ACCOUNT ARTICLES (150 total)
-- =====================================================

BEGIN;

INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('User Registration',
        'Create your account: To get started: 1. Click "Sign Up" button on homepage 2. Enter your email address 3. Create password (minimum 8 characters) 4. Select your user type (Customer, Staff, Admin) 5. Fill in required information 6. Verify your email address 7. Click verification link',
        'ACCOUNT',
        10,
        ARRAY ['registration', 'sign up', 'email', 'password', 'verify'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Complete Profile',
        'Fill in your profile: Go to Settings > Profile. Required fields: Full Name, Email, Phone Number (optional), Company Name (if applicable), Address fields. Optional: Profile picture, Timezone',
        'ACCOUNT',
        9,
        ARRAY ['profile', 'name', 'email', 'phone', 'company', 'address', 'timezone'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Company Profile',
        'Company account setup: For business users: 1. Complete Company Profile section 2. Add company information: name, address, phone, industry 3. Upload company logo (optional) 4. Set billing preferences 5. Designate billing contacts',
        'ACCOUNT',
        8,
        ARRAY ['company', 'profile', 'logo', 'billing contacts'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Multi-User Setup',
        'Add team members: Go to Settings > Team > Add Member. Enter member email address and select role. Available roles: ADMIN, SUPERVISOR, AGENT, CUSTOMER. Member receives email invitation and sets password.',
        'ACCOUNT',
        7,
        ARRAY ['team', 'members', 'roles', 'invite'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Tier Upgrade/Downgrade',
        'Change subscription tier: Go to Settings > Subscription > Change Plan. Select desired tier. Confirm changes. Note: Prorated features may be affected.',
        'ACCOUNT',
        6,
        ARRAY ['tier', 'subscription', 'upgrade', 'downgrade', 'prorated'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Email Verification',
        'Verify email address: Click link in verification email. Resend verification if needed. Email remains unverified until confirmed.',
        'ACCOUNT',
        5,
        ARRAY ['email', 'verify', 'verification link', 'resend'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Account Status',
        'Account status indicators: ACTIVE: Full access, SUSPENDED: Login disabled, CLOSED: Account deleted. View status in dashboard or check for email notifications.',
        'ACCOUNT',
        4,
        ARRAY ['account status', 'active', 'suspended', 'closed'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Password Requirements',
        'Password policy: Minimum 8 characters, mix of letters, numbers, symbols. Cannot use common passwords. Must be different from last 5 passwords.',
        'ACCOUNT',
        10,
        ARRAY ['password', 'requirements', 'complexity', 'change', 'common'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Account Deletion',
        'Delete account process: Submit deletion request. Provide reason. 30-day data retention before permanent deletion. Download data if needed.',
        'ACCOUNT',
        2,
        ARRAY ['delete', 'account', 'deletion', 'retention', 'data'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Notification Preferences',
        'Manage notifications: Go to Settings > Notifications. Configure: Email notifications (ticket updates, responses, reminders), In-app notifications, Browser notifications (desktop). Disable if unwanted.',
        'ACCOUNT',
        5,
        ARRAY ['notifications', 'email', 'in-app', 'browser', 'disable'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Address Management',
        'Multiple addresses: Add, edit, remove addresses. Set primary address. Different addresses for billing vs shipping.',
        'ACCOUNT',
        6,
        ARRAY ['address', 'multiple', 'primary', 'billing', 'shipping'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Timezone Settings',
        'Set timezone: Go to Settings > General. Select timezone from list. Affects: Dashboard display, scheduled task times, notification timing.',
        'ACCOUNT',
        4,
        ARRAY ['timezone', 'display', 'schedule', 'notifications'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Consent Management',
        'Privacy consent: View and update consents. Required for: Terms of Service, Privacy Policy, Marketing Communications. Manage cookie preferences.',
        'ACCOUNT',
        5,
        ARRAY ['consent', 'privacy', 'terms', 'cookies', 'marketing'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Account Recovery',
        'Recover locked account: If locked, use "Forgot Password" to reset password. If 2FA enabled, may need 2FA code.',
        'ACCOUNT',
        3,
        ARRAY ['locked', 'recovery', 'password reset', '2fa'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Linked Accounts',
        'Social media linking: Connect accounts: Go to Settings > Account > Social. Add social accounts (Facebook, Twitter/X, LinkedIn). View connected accounts and manage permissions.',
        'ACCOUNT',
        4,
        ARRAY ['social', 'connect', 'linked accounts', 'permissions'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('API Keys',
        'API key management: For developers/integrations: Generate API keys. Set permissions. Rotate keys regularly. Delete unused keys.',
        'ACCOUNT',
        3,
        ARRAY ['api', 'keys', 'generate', 'permissions', 'rotate'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Audit Logs',
        'View account activity: Go to Settings > Audit Logs. Shows: Login history, profile changes, security events, API usage. Filter by date and event type.',
        'ACCOUNT',
        5,
        ARRAY ['audit', 'logs', 'login history', 'security events'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Billing Access',
        'Billing delegation: For corporate accounts: Designate billing contacts. Multiple users can view billing information based on permissions.',
        'ACCOUNT',
        4,
        ARRAY ['billing', 'delegation', 'contacts', 'permissions'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Purchase History',
        'View purchase history: See all transactions and invoices. Export to CSV. Search by date, amount, or payment method.',
        'ACCOUNT',
        4,
        ARRAY ['purchase', 'history', 'invoices', 'export', 'search'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Security Settings',
        'Enhance security: Enable security notifications. Add trusted devices. Review authorized apps. Enable login alerts from new devices.',
        'ACCOUNT',
        9,
        ARRAY ['security', 'notifications', 'trusted devices', 'login alerts', 'authorized apps'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Integration Settings',
        'Configure integrations: Connect CRM tools. Set up webhooks. Configure data sync intervals. Monitor integration health.',
        'ACCOUNT',
        5,
        ARRAY ['integration', 'crm', 'webhook', 'sync', 'monitor'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Account Merging',
        'Merge duplicate accounts: If you have multiple accounts, contact support to merge. Duplicate accounts may cause billing and access issues.',
        'ACCOUNT',
        2,
        ARRAY ['merge', 'duplicate accounts', 'contact support'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Role Management',
        'Role assignment: For admins: Assign roles to users. For supervisors: Add team members. For agents: View assigned tickets and queue.',
        'ACCOUNT',
        7,
        ARRAY ['roles', 'assign', 'team members', 'permissions'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Compliance',
        'Compliance requirements: Data retention: 30-day policy after deletion. Email verification required. API rate limits apply.',
        'ACCOUNT',
        3,
        ARRAY ['compliance', 'data retention', 'verification', 'rate limits'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0);

COMMIT;

-- =====================================================
-- SHIPPING ARTICLES (170 total)
-- =====================================================

BEGIN;

INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Track Order Status',
        'Track your order: 1. Go to Orders page or click order number 2. View order status (Processing, Shipped, In Transit, Delivered, Cancelled) 3. See tracking number and carrier information',
        'SHIPPING',
        10,
        ARRAY ['order tracking', 'status', 'tracking number', 'carrier'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('View Order Details',
        'View order details: Order details: Items ordered, quantities, prices, shipping address, billing information. Tracking updates in real-time.',
        'SHIPPING',
        9,
        ARRAY ['order details', 'items', 'quantities', 'shipping address', 'tracking'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Shipping Methods',
        'Available shipping: Standard Shipping (5-7 business days, free over $50), Express Shipping (2-3 business days, fee applies), Overnight Shipping (next business day, higher fee). Select at checkout.',
        'SHIPPING',
        8,
        ARRAY ['shipping', 'standard', 'express', 'overnight', 'fee', 'checkout'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Shipping Address',
        'Manage shipping addresses: Add, edit, remove addresses. Set primary shipping address. Different addresses for billing vs shipping.',
        'SHIPPING',
        7,
        ARRAY ['address', 'multiple', 'primary', 'shipping'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Delivery Options',
        'Delivery preferences: Instructions for carriers: Leave at door for residential delivery. Doorman available for apartments. Sign for package.',
        'SHIPPING',
        6,
        ARRAY ['delivery', 'carrier instructions', 'doorman', 'sign for'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Package Tracking',
        'Live tracking updates: Receive notifications: Email/SMS updates for status changes. See estimated delivery date and time window.',
        'SHIPPING',
        9,
        ARRAY ['tracking', 'notifications', 'delivery date', 'time window'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Missing Package',
        'Report missing package: 1. Click "Report Issue" on order 2. Describe issue (package not received, damaged item, wrong item) 3. Attach photos if available 4. Support team will investigate',
        'SHIPPING',
        10,
        ARRAY ['missing package', 'report issue', 'photos', 'investigation'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Wrong Address',
        'Wrong delivery address: If delivered to wrong address: 1. Contact support immediately 2. Package may need to be re-routed (additional fees may apply)',
        'SHIPPING',
        7,
        ARRAY ['wrong address', 're-route', 'additional fees'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Package Held',
        'Package on hold: If package is held at carrier facility: 1. Wait for release from hold 2. Contact support if delay exceeds 3 days 3. Request expedited shipping if urgent',
        'SHIPPING',
        6,
        ARRAY ['held', 'carrier facility', 'delay', 'expedited'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Damaged Package',
        'Damaged in transit: 1. Document damage: Take photos of damage and packaging 2. Report immediately through order or support 3. Keep all packaging for carrier inspection',
        'SHIPPING',
        10,
        ARRAY ['damaged', 'photos', 'report', 'inspection', 'carrier'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('International Shipping',
        'International orders: Additional considerations: Customs: May be subject to import duties and taxes. Delivery time: 7-21 business days. Tracking: International tracking available.',
        'SHIPPING',
        5,
        ARRAY ['international', 'customs', 'duties', 'taxes', 'delivery time'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Return Shipping',
        'Return process: Initiate return: 1. Click "Return Item" in order 2. Select return reason (wrong item, damaged, no longer needed) 3. Print return shipping label 4. Package and drop off 5. Wait for refund after processing (5-7 business days)',
        'SHIPPING',
        9,
        ARRAY ['return', 'return reason', 'shipping label', 'refund timeline'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Partial Shipment',
        'Partial shipments: If split shipment: Order may be split into multiple shipments. Each shipment has its own tracking number. All items will be delivered across shipments.',
        'SHIPPING',
        6,
        ARRAY ['split shipment', 'multiple tracking', 'separate shipments'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Shipping Costs',
        'Shipping fees: Base shipping fee + Additional services: Insurance: $2.99 per $100, Signature Required: $3.99, Handling Fee: Varies by size. Expedited Shipping: 2-3 day fee + base rate.',
        'SHIPPING',
        8,
        ARRAY ['shipping fees', 'insurance', 'signature', 'expedited', 'handling fee'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Carrier Information',
        'Carrier details: Contact carriers directly: Use carrier phone number or website for updates. Check service updates for delays.',
        'SHIPPING',
        5,
        ARRAY ['carrier', 'contact', 'updates', 'service disruptions'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Address Validation',
        'Address verification: Address format validation: Use standard address format. Address suggestions: Ensure city and postal code match. Invalid addresses will be flagged at checkout.',
        'SHIPPING',
        7,
        ARRAY ['address validation', 'format', 'suggestions', 'flag'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Delivery Instructions',
        'Special delivery: Specific instructions: Leave package at front desk. Provide access code for buildings. Use doorman service for apartments.',
        'SHIPPING',
        6,
        ARRAY ['delivery instructions', 'front desk', 'access code', 'doorman'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Package Consolidation',
        'Combine orders: Save on shipping: Orders placed within 24 hours may be combined for shipping (if items are in stock and from same warehouse).',
        'SHIPPING',
        4,
        ARRAY ['combine', 'save on shipping', 'multiple orders', 'stock'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Shipping Notifications',
        'Delivery alerts: SMS notifications: Get real-time updates on delivery status. Email notifications: Daily digest for orders. Push notifications for mobile app.',
        'SHIPPING',
        6,
        ARRAY ['notifications', 'sms', 'email digest', 'push'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Pickup Points',
        'Self-pickup: For local pickup: Choose at checkout. You will receive notification when order is ready. Bring ID and photo if required.',
        'SHIPPING',
        5,
        ARRAY ['self-pickup', 'checkout', 'notification', 'id'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Freight Forwarding',
        'Freight orders: For larger orders: Contact support for freight quote. Freight delivery: 7-14 business days. Requires commercial address. Tracking: Same as standard shipments.',
        'SHIPPING',
        3,
        ARRAY ['freight', 'commercial address', 'delivery time', 'tracking'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0);

COMMIT;

-- =====================================================
-- SECURITY ARTICLES (100 total)
-- =====================================================

BEGIN;

INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Security Overview',
        'Account security: Protect your account with strong password and enable 2FA. Regularly review account activity for unauthorized access. Report suspicious activity immediately.',
        'SECURITY',
        10,
        ARRAY ['account security', 'password', '2fa', 'unauthorized access', 'suspicious activity'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Phishing Awareness',
        'Recognize phishing: Be cautious of: Fake emails from legitimate-looking addresses asking for login credentials or payment information. Verify sender email address. Never click suspicious links.',
        'SECURITY',
        10,
        ARRAY ['phishing', 'fake emails', 'verify sender', 'suspicious links'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Secure Login',
        'Secure login practices: 1. Check URL for HTTPS (padlock icon) 2. Verify domain name in address bar 3. Use password manager for unique passwords 4. Never save passwords in browser 5. Log out from shared devices',
        'SECURITY',
        10,
        ARRAY ['secure login', 'https', 'password manager', 'shared devices'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Password Security',
        'Password best practices: Use unique password: Never reuse passwords across different sites. Change password regularly (every 90 days). Password complexity: Minimum 8 characters, mix of letters, numbers, and symbols.',
        'SECURITY',
        10,
        ARRAY ['password security', 'unique', 'change regularly', 'complexity'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Device Security',
        'Device management: Trusted devices: Use only your devices on public networks. Device encryption: Enable device encryption if supported. Remote wipe: Remotely wipe data from lost or stolen devices.',
        'SECURITY',
        9,
        ARRAY ['device security', 'trusted devices', 'encryption', 'remote wipe'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Data Privacy',
        'Data protection: How we protect your data: Data encryption: All data encrypted at rest and in transit. Access control: Based on your role and permissions. Data retention: 30-day policy for deleted accounts.',
        'SECURITY',
        10,
        ARRAY ['data protection', 'encryption', 'access control', 'retention'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Privacy Settings',
        'Privacy controls: Manage your privacy: Go to Settings > Privacy. Configure: Data sharing, Marketing preferences, Cookie settings. Manage connected apps and their permissions.',
        'SECURITY',
        8,
        ARRAY ['privacy', 'data sharing', 'marketing', 'cookies', 'connected apps'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Security Monitoring',
        'Security alerts: Suspicious activity: If unusual activity detected, you will be logged out and prompted to verify identity. Login from new device: Verify new devices before granting access.',
        'SECURITY',
        7,
        ARRAY ['security monitoring', 'suspicious activity', 'new device', 'logout'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Account Recovery',
        'Recovery options: Self-recovery: Use "Forgot Password" to reset. Support recovery: Contact security team if account compromised.',
        'SECURITY',
        5,
        ARRAY ['recovery', 'forgot password', 'security team'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('API Security',
        'API security: API key protection: Generate keys with appropriate permissions. Rotate keys regularly (every 90 days). Use environment variables: Never expose API keys in code or client-side storage.',
        'SECURITY',
        6,
        ARRAY ['api security', 'keys', 'rotate', 'environment variables', 'exposure'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Session Security',
        'Session management: Auto-logout: Sessions expire after 30 minutes of inactivity. Device management: View and revoke devices. Concurrent logins: Limited to 5 active sessions per account.',
        'SECURITY',
        6,
        ARRAY ['session management', 'auto-logout', 'device management', 'concurrent logins'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Fraud Prevention',
        'Fraud detection: Verify requests: Confirm official requests through secure channels. Report fraud: Forward suspicious emails to spoof@domain.com. Payment verification: Verify payment pages are legitimate before entering information.',
        'SECURITY',
        9,
        ARRAY ['fraud prevention', 'verify requests', 'report phishing', 'payment verification'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Social Engineering',
        'Social media security: Review connected apps: Regularly review app permissions. Remove unnecessary connections. Privacy settings: Check app privacy settings and limit data sharing.',
        'SECURITY',
        7,
        ARRAY ['social media', 'app permissions', 'privacy settings'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Vulnerability Reporting',
        'Report vulnerabilities: Responsible disclosure: If you discover a security vulnerability, report it responsibly. Do not exploit vulnerabilities. Contact security team for guidance.',
        'SECURITY',
        5,
        ARRAY ['vulnerability', 'responsible disclosure', 'security team'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Secure Communication',
        'Secure communication: Email security: Verify email comes from legitimate source. Check for email spoofing (wrong domain, slight misspelling). Use official channels only.',
        'SECURITY',
        9,
        ARRAY ['secure communication', 'email verification', 'spoofing', 'official channels'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Mobile Security',
        'Mobile security: App updates: Keep app updated. Public WiFi: Avoid using public WiFi for sensitive transactions. Device security: Enable screen lock and biometrics if available.',
        'SECURITY',
        7,
        ARRAY ['mobile security', 'app updates', 'public wifi', 'screen lock', 'biometrics'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0);

COMMIT;

-- =====================================================
-- GENERAL ARTICLES (200 total)
-- =====================================================

BEGIN;

INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Getting Started',
        'Welcome to the platform: 1. Create your account by clicking "Sign Up" 2. Choose your user type (Customer for personal use, Business for company use, Staff for team management) 3. Complete your profile with required information 4. Verify your email address',
        'OTHER',
        10,
        ARRAY ['getting started', 'sign up', 'verify email', 'profile'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Dashboard Overview',
        'Navigate the dashboard: The dashboard is your central hub. Access tickets, view notifications, manage settings, and track analytics. Key sections: Tickets, Notifications, Settings, Analytics, Help.',
        'OTHER',
        9,
        ARRAY ['dashboard', 'tickets', 'notifications', 'settings', 'analytics'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Support Process',
        'How to get help: Create a ticket: Click "New Ticket" and describe your issue. Ticket number: Format: TKT-00001234. Response time: We typically respond within 24 hours. Priority levels: CRITICAL (immediate), HIGH(24 hours), MEDIUM(48 hours), LOW(72 hours).',
        'OTHER',
        8,
        ARRAY ['ticket', 'creation', 'ticket number', 'response time', 'priority levels'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Ticket Status Flow',
        'Understanding ticket lifecycle: Status flow: RECEIVED (new ticket) -> TRIAGING (AI analysis) -> WAITING_CUSTOMER (clarification) or ASSIGNED (to agent) -> IN_PROGRESS (agent working) -> RESOLVED (issue fixed) -> CLOSED (customer confirmed)',
        'OTHER',
        9,
        ARRAY ['ticket lifecycle', 'status flow', 'triaging', 'assigned', 'in progress', 'resolved', 'closed'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Autonomous Resolution',
        'AI-powered ticket resolution: Our AI assistant can automatically resolve many tickets: 1. Quick issues: Password resets, order status queries (70-80% auto-resolution rate) 2. Pattern-based: Common issues with established solutions 3. Multi-turn: Clarifying questions to gather more information',
        'OTHER',
        10,
        ARRAY ['ai resolution', 'auto-resolution rate', 'clarifying questions', 'patterns'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Priority System',
        'Ticket priority explained: CRITICAL: System-wide issues affecting all users. No SLA. Response within 1 hour. HIGH: Urgent issues affecting your account or orders. Response within 24 hours. MEDIUM: General inquiries. Response within 48 hours. LOW: Enhancement requests. Response within 72 hours.',
        'OTHER',
        8,
        ARRAY ['priority', 'critical', 'urgent', 'high', 'medium', 'low'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Escalation Process',
        'When to escalate: If your issue requires specialized handling: 1. Complex technical problems 2. Billing disputes or large refunds 3. Security concerns 4. Management requests. Escalation may take 1-2 business days. Supervisor involvement required.',
        'OTHER',
        6,
        ARRAY ['escalation', 'technical', 'billing', 'security', 'management'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Feedback',
        'Share your experience: After resolution: Rate your experience (1-5 stars). Provide feedback: Helps us improve. Optional comments: Share details about what worked well or what could be better.',
        'OTHER',
        7,
        ARRAY ['feedback', 'rating', 'improve', 'comments'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Communication Channels',
        'How we communicate: Email: For non-urgent issues (response within 24 hours). Phone: For urgent issues (available during business hours). In-app: Real-time notifications and updates.',
        'OTHER',
        8,
        ARRAY ['communication', 'email', 'phone', 'in-app', 'response time'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Privacy & Data',
        'Your privacy matters: Data collection: We collect account information, ticket content, and feedback. Usage: Used to improve services. Sharing: Never sell or share your data. Protection: Encrypted storage, access controls, regular security audits.',
        'OTHER',
        9,
        ARRAY ['privacy', 'data collection', 'usage', 'encryption', 'access controls'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0),
       ('Terms of Service',
        'Service terms: By using our platform: You agree to our Terms of Service and Privacy Policy. Acceptable Use: Personal and business use. Prohibited uses: Spam, fraud, harassment, illegal activities.',
        'OTHER',
        8,
        ARRAY ['terms of service', 'acceptable use', 'prohibited uses'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Platform Features',
        'Key features: Knowledge Base: AI-powered articles to help resolve issues quickly. Analytics: Track your account activity and support metrics. Customization: Customize your dashboard and notification preferences.',
        'OTHER',
        9,
        ARRAY ['features', 'knowledge base', 'analytics', 'customization'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Help Center',
        'Get additional help: Browse our Help Center for: 1. FAQ articles: Searchable knowledge base 2. Video tutorials: Step-by-step guides 3. Contact options: Email, phone, live chat (during business hours). Community: User forums and discussions.',
        'OTHER',
        8,
        ARRAY ['help center', 'faq', 'video tutorials', 'contact options', 'community'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Account Settings',
        'Personalize your experience: Notification preferences: Choose email, SMS, or in-app notifications. Control frequency: Daily, weekly, monthly, or as-they-happen. Theme selection: Light, dark, or automatic based on system settings.',
        'OTHER',
        7,
        ARRAY ['settings', 'notifications', 'frequency', 'theme'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Language Support',
        'Multiple languages: The platform supports: English (primary), with additional languages available in future. Translation: Some content may be auto-translated. Interface: Available in your selected language.',
        'OTHER',
        4,
        ARRAY ['language', 'english', 'translation', 'interface'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Mobile App',
        'On-the-go support: Download the app: Available on iOS and Android. Features: Push notifications for urgent tickets. Offline access: View ticket history and status updates without internet connection.',
        'OTHER',
        6,
        ARRAY ['mobile app', 'download', 'push notifications', 'offline access', 'ios', 'android'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Tips & Best Practices',
        'Efficiency tips: Write clear ticket subjects: Include relevant details (order number, error messages). Provide context: Share previous ticket numbers related to your issue. Attach files: Screenshots and error messages help expedite resolution.',
        'OTHER',
        9,
        ARRAY ['tips', 'best practices', 'ticket subjects', 'context', 'attachments'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Accessibility',
        'Platform accessibility: Keyboard navigation: Use Tab to navigate. Screen reader compatibility: Works with major screen readers. Color contrast: High contrast mode available. Text size: Adjustable font size throughout the application.',
        'OTHER',
        5,
        ARRAY ['accessibility', 'keyboard', 'screen reader', 'high contrast', 'text size'],
        'QUICK_SOLUTION',
        true,
        0,
        0,
        0);

COMMIT;

-- =====================================================
-- ENRICHMENT - Additional High-Value Articles
-- =====================================================

BEGIN;

-- Additional BILLING Articles
INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Subscription Pause Request',
        'To pause your subscription: 1. Go to Settings > Subscription 2. Click "Pause Subscription" 3. Select pause duration (1-3 months) 4. Confirm. During pause: Account frozen, no charges, limited access. Resume anytime from Settings.',
        'BILLING',
        7,
        ARRAY ['subscription', 'pause', 'freeze', 'resume'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Payment Dispute',
        'To dispute a charge: 1. Go to Settings > Billing > Transaction History 2. Find the transaction 3. Click "Dispute" 4. Select dispute reason (unauthorized, duplicate, incorrect amount) 5. Add supporting documentation 6. Submit. We will investigate within 10 business days.',
        'BILLING',
        8,
        ARRAY ['payment', 'dispute', 'unauthorized', 'duplicate', 'investigation'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Tax Exemption',
        'Tax exemption for eligible organizations: 1. Go to Settings > Billing 2. Upload tax exemption certificate 3. Select exemption type (non-profit, government, education) 4. Submit. Verification takes 5-7 business days. Once approved, future invoices will show 0 tax.',
        'BILLING',
        6,
        ARRAY ['tax', 'exemption', 'non-profit', 'government', 'education'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Payment Method Limit',
        'Understanding payment method limits: Maximum cards: 5 per account. Debit cards: 3 per account. PayPal: 2 per account (verified only). Prepaid cards: Not accepted. To add new card: Remove old card first if at limit.',
        'BILLING',
        5,
        ARRAY ['payment method', 'limit', 'card', 'paypal', 'prepaid'],
        'FAQ',
        true,
        0,
        0,
        0);

-- Additional TECHNICAL Articles
INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Webhook Configuration',
        'Setting up webhooks: 1. Go to Settings > Integrations > Webhooks 2. Add webhook URL (must use HTTPS) 3. Select events to trigger (ticket.created, ticket.updated, ticket.closed) 4. Generate secret key 5. Test webhook. Status codes: 200 (success), 400 (bad request), 401 (unauthorized).',
        'TECHNICAL',
        7,
        ARRAY ['webhook', 'integration', 'api', 'https', 'events'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('SSO Single Sign-On',
        'Configure SSO for enterprise: 1. Go to Settings > Security > SSO 2. Select SSO provider (SAML 2.0, OIDC) 3. Upload metadata file (XML or JSON) 4. Configure attribute mapping 5. Test connection. Requires: ENTERPRISE tier. Benefits: Centralized auth, passwordless login.',
        'TECHNICAL',
        6,
        ARRAY ['sso', 'single sign-on', 'saml', 'oidc', 'enterprise', 'authentication'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Export Data Request',
        'Request account data export: 1. Go to Settings > Privacy > Export Data 2. Select data types (tickets, messages, profile, billing) 3. Choose format (JSON, CSV, PDF) 4. Request export. Large requests (>1000 records) may take 24-48 hours to process. Download link valid for 7 days.',
        'TECHNICAL',
        8,
        ARRAY ['export', 'data', 'privacy', 'gdpr', 'json', 'csv'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Browser Extension Issues',
        'Browser extension not working: 1. Clear extension cache 2. Disable and re-enable extension 3. Check for updates in extension store 4. Try in incognito mode 5. Conflicting extensions: Disable temporarily. If still issues: Contact support with browser version and extension version.',
        'TECHNICAL',
        5,
        ARRAY ['browser', 'extension', 'cache', 'update', 'conflict'],
        'TROUBLESHOOTING',
        true,
        0,
        0,
        0);

-- Additional ACCOUNT Articles
INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Profile Picture Upload',
        'Upload profile picture: 1. Go to Settings > Profile 2. Click "Upload Photo" 3. Select image file (JPG, PNG, max 5MB) 4. Crop and adjust 5. Save. Recommended: Professional headshot, 400x400 pixels minimum. Avoid: Blurry images, filters, text overlays.',
        'ACCOUNT',
        5,
        ARRAY ['profile', 'picture', 'photo', 'upload', 'avatar'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Two-Factor Backup Codes',
        'Backup codes for 2FA: 1. Go to Settings > Security > 2FA 2. Click "Generate Backup Codes" 3. Generate 10 single-use codes 4. Save codes securely (offline safe) 5. Use when authenticator app unavailable. Each code: Single use only. Regenerate when 3 or fewer codes remain.',
        'ACCOUNT',
        9,
        ARRAY ['2fa', 'backup codes', 'authenticator', 'recovery'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Email Notifications Frequency',
        'Control email notification frequency: 1. Go to Settings > Notifications > Email 2. Select frequency: Instant, Daily Digest, Weekly Summary, Monthly Report 3. For each category: Tickets, System, Marketing 4. Customize sender preferences 5. Save. Instant: Recommended for critical issues. Digest: Reduces email clutter.',
        'ACCOUNT',
        6,
        ARRAY ['notifications', 'email', 'frequency', 'digest', 'instant'],
        'FAQ',
        true,
        0,
        0,
        0);

-- Additional SHIPPING Articles
INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Package Redelivery',
        'Request package redelivery: 1. Go to Orders page 2. Find delivered order 3. Click "Request Redelivery" 4. Select reason (wrong address, missed delivery) 5. Confirm new address 6. Submit. Redelivery fee: May apply if address error was customer fault. Timeframe: 1-3 business days depending on carrier.',
        'SHIPPING',
        8,
        ARRAY ['redelivery', 'package', 'missed delivery', 'address'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Delivery Appointment',
        'Schedule delivery appointment: For large/heavy items requiring signature: 1. Check order for "Appointment Required" 2. Click "Schedule Delivery" 3. Select date/time from available slots 4. Add delivery instructions 5. Confirm. Available slots: 2-hour windows, Monday-Friday 8AM-6PM. Changes: Modify up to 24 hours before appointment.',
        'SHIPPING',
        7,
        ARRAY ['delivery', 'appointment', 'schedule', 'large item', 'signature'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Shipping Insurance Claim',
        'File shipping insurance claim: 1. Document damage immediately (photos of item, packaging, shipping label) 2. Go to Orders > File Claim 3. Select order and damage type 4. Upload documentation 5. Describe incident 6. Submit. Process time: 14-21 business days. Covered: Damaged, lost, stolen items. Not covered: Customer refused package, wrong address.',
        'SHIPPING',
        9,
        ARRAY ['insurance', 'claim', 'damage', 'lost', 'stolen', 'refund'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0);

-- Additional SECURITY Articles
INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('OAuth2 Application Setup',
        'Register OAuth2 application: 1. Go to Developer Portal > Applications 2. Click "Create App" 3. Enter app name, description, redirect URL 4. Select scopes (read tickets, write tickets, read profile) 5. Upload logo 6. Submit. Receive: client_id and client_secret. Best practices: Use PKCE, store secrets securely, implement refresh tokens.',
        'SECURITY',
        6,
        ARRAY ['oauth2', 'application', 'api', 'developer', 'client_id'],
        'PROCEDURAL_GUIDE',
        true,
        0,
        0,
        0),
       ('Rate Limiting',
        'Understanding API rate limits: Limits: 1000 requests/minute, 10000 requests/hour per API key. Headers included: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset. When exceeded: HTTP 429 (Too Many Requests). Retry strategy: Exponential backoff, respect Retry-After header. Enterprise tier: Higher limits available on request.',
        'SECURITY',
        5,
        ARRAY ['rate limit', 'api', 'throttling', '429', 'backoff'],
        'FAQ',
        true,
        0,
        0,
        0);

-- Additional OTHER Articles
INSERT INTO knowledge_article (title,
                               content,
                               category,
                               priority,
                               keywords,
                               article_type,
                               active,
                               usage_count,
                               success_count,
                               failure_count)
VALUES ('Mobile App Permissions',
        'Mobile app permissions explained: Location: Used for local support centers (optional). Camera: Required for uploading profile photos (optional). Push notifications: Required for real-time ticket updates (recommended). Storage: Required for offline access (minimal). Contacts: Used for easy ticket creation (optional). Manage: Go to Settings > Privacy on mobile app.',
        'OTHER',
        5,
        ARRAY ['mobile', 'app', 'permissions', 'privacy', 'location', 'camera'],
        'FAQ',
        true,
        0,
        0,
        0),
       ('Keyboard Shortcuts',
        'Keyboard shortcuts for power users: Dashboard: D (new ticket), / (search), ? (help). Ticket view: R (reply), E (edit), C (close). Navigation: G+H (home), G+K (knowledge base). Customize: Settings > Keyboard > Edit shortcuts. Benefits: Faster navigation, reduced mouse usage.',
        'OTHER',
        4,
        ARRAY ['keyboard', 'shortcuts', 'productivity', 'navigation', 'accessibility'],
        'FEATURE_OVERVIEW',
        true,
        0,
        0,
        0);

COMMIT;
